disabled_rules: # rule identifiers to exclude from running
# - closing_brace
# - colon
# - comma
# - control_statement
- cyclomatic_complexity
# - file_length
# - force_cast
# - force_try
# - function_body_length
- function_parameter_count
# - leading_whitespace
# - legacy_cggeometry_functions
# - legacy_constant
# - legacy_constructor
# - line_length
- nesting
# - opening_brace
# - operator_whitespace
# - return_arrow_whitespace
# - statement_position
- todo
# - trailing_newline
# - trailing_semicolon
# - trailing_whitespace
# - type_body_length
# - type_name
- valid_docs
# - variable_name
opt_in_rules: # some rules are only opt-in
  - empty_count
  # - force_unwrapping
  # - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
whitelist_rules:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 130
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
  - iPhone
  - iPad
  - API
function_parameter_count:
  warning: 3
  error: 6
cyclomatic_complexity:
  warning: 2
  error: 6
variable_name:
  min_length: 2 # only min_length
  error: 4 # only error
  excluded: # excluded via string array
  - id
  - URL
  - API
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
