fastlane_version "2.0.0"

default_platform :ios

platform :ios do
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cocoapods
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Today") # Build your app - more options available
    pilot
  end

  desc "Fetches the certificates and provisioning profiles to run the project."
  lane :certs do
    match(type: "development")
    match(type: "appstore")
  end

end
